plugins:
    - jekyll-seo-tag
    - jekyll-github-metadata
    - jekyll-redirect-from
    - jekyll-sitemap

theme: jekyll-theme-minimal
    
url           : "https://infominer.id/bitcoin-history"
baseurl       : "/bitcoin-history"
title         : "Bitcoin Historical Index"
description   : "The History Surrounding Bitcoin, including Pre-History and Immediately Related Fields."
author        : "â§‰ Infominer"
logo          : "https://infominer.id/images/og-image.jpg"
repository    : "infominer33/bitcoin-history"
github        : [metadata]


twitter:
  site        : "infominer33"
  title       : "Bitcoin Historical Index"
  description : "The History Surrounding Bitcoin, including Pre-History and Immediately Related Fields."
  image       : "https://infominer.id/DIDecentralized/infominer.png"
  card        : "summary"
 
google_analytics: UA-132558656-1